
POST http://localhost:8000/comment/register/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
    "content": "Este é um comentário de exemplo.",
    "forum_slug": "centro-seguranca-e-emergencias"
}

######

POST http://localhost:8000/comment/edit/41/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
    "content": "Comentário editado"
}

######

POST http://localhost:8000/comment/delete/41/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

####### 

GET http://localhost:8000/comment/list/centro-seguranca-e-emergencias/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

####### 


GET http://localhost:8000/comment/report/list/centro-seguranca-e-emergencias/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json


### Teste: Adicionar um Like
POST http://127.0.0.1:8000/comment/like/42/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
  "is_like": true
}

### Teste: Adicionar um Dislike
POST http://127.0.0.1:8000/comment/dislike/42/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
  "is_like": false
}

### Teste: Remover Like/Dislike
DELETE http://127.0.0.1:8000/comment/unlike/42/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52

########




POST http://localhost:8000/comment/report/register/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
    "content": "Este é um report de exemplo.",
    "title":"perigo",
    "location":"rua das flores",
    "tag": "SG",
    "solved": "False",
    "forum_slug": "centro-seguranca-e-emergencias"
}


#######

POST http://localhost:8000/comment/report/edit/42/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
    "content": "Este é um report de exemplo.",
    "title":"cuidado",
    "location":"rua das flores",
    "tag": "SA",
    "solved": "False",
    "forum_slug": "centro-seguranca-e-emergencias"
}

######

POST http://localhost:8000/comment/delete/42/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

####### 

### Criar uma Pool com opções associadas
POST http://localhost:8000/comment/pool/register/
Content-Type: application/json
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52

{
    "title": "Qual é o seu framework favorito?",
    "content": "Escolha um dos frameworks abaixo.",
    "deadline": "2025-12-31",
    "forum_slug": "centro-seguranca-e-emergencias",
    "options": [
        {"option_text": "Django"},
        {"option_text": "Flask"},
        {"option_text": "FastAPI"}
    ]
}

####### 

GET http://localhost:8000/comment/pool/list/centro-seguranca-e-emergencias/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52


####### 
POST http://localhost:8000/comment/vote/7/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52

####### 

POST http://localhost:8000/comment/unvote/7/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52

####### 