
POST http://localhost:8000/comment/register/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

{
    "content": "Este é um comentário de exemplo.",
    "forum": 1 
}

######

POST http://localhost:8000/comment/edit/3/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

{
    "content": "Comentário para ser deletado"
}

######

POST http://localhost:8000/comment/delete/3/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

######