# Generated by Django 5.1.4 on 2025-01-19 16:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='perfil_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path),
        ),
    ]
