# Generated by Django 5.1.4 on 2025-01-19 22:51

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image_low',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.directory_path),
        ),
    ]
