# Generated by Django 5.1.3 on 2025-01-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_trust_rate_commentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
