# Generated by Django 5.1.3 on 2025-01-19 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_pool_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='comment.pool'),
        ),
    ]
