# Generated by Django 5.1.3 on 2025-01-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
