# Generated by Django 5.1.3 on 2025-01-20 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_option_pool'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comment.option')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'option')},
            },
        ),
    ]
