# Generated by Django 5.1.3 on 2025-01-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_post_date'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.comment')),
                ('tag', models.CharField(choices=[('S', 'Saúde'), ('L', 'Lixo'), ('I', 'Infraestrutura'), ('SG', 'Segurança'), ('E', 'Educação'), ('T', 'Transporte'), ('IL', 'Iluminação'), ('O', 'Outros')], default='O', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('location', models.TextField(max_length=1023)),
                ('solved', models.BooleanField(default=False)),
            ],
            bases=('comment.comment',),
        ),
        migrations.RenameModel(
            old_name='CommentLike',
            new_name='Like',
        ),
    ]
