# Generated by Django 5.1.4 on 2025-01-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_post_date'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.comment')),
                ('tag', models.CharField(choices=[('S', 'Saúde'), ('L', 'Lixo'), ('I', 'Infraestrutura'), ('SG', 'Segurança'), ('E', 'Educação'), ('T', 'Transporte'), ('IL', 'Iluminação'), ('RG', 'Rede de proteção (guardião)'), ('O', 'Outros')], default='O', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('location', models.TextField(max_length=1023)),
                ('solved', models.BooleanField(default=False)),
            ],
            bases=('comment.comment',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_like', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comment.comment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('comment', 'user_profile')},
            },
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
