# Generated by Django 5.1.3 on 2025-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_report_rename_commentlike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('C', 'comment'), ('R', 'report')], default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('SA', 'Saúde'), ('L', 'Lixo'), ('I', 'Infraestrutura'), ('SG', 'Segurança'), ('E', 'Educação'), ('T', 'Transporte'), ('IL', 'Iluminação'), ('O', 'Outros')], default='O', max_length=5),
        ),
    ]
