
POST http://localhost:8000/forum/register/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

{
  "title": "norte",
  "description": "This is an example description for the forum."
}

######

POST  http://localhost:8000/forum/edit/norte-4/ 
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

{
  "title": "ano novo 200",
  "description": "This is an example description for the forum."
}

######

POST  http://localhost:8000/forum/delete/teste/ HTTP/1.1
Authorization: Token 0b32659e7c17349859dd9e123c9ace264aed9520
Content-Type: application/json

######

GET http://localhost:8000/forum/list/?page=1
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52

######

GET http://localhost:8000/forum/list/?search=natal
Authorization: Token c55d674ffd9e375f61d3be0a32c5d7f6403404a1

######

POST http://localhost:8000/forum/subscribe/natal-mexicano-5/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52

### Testar Cancelamento de Inscrição no Fórum
POST http://127.0.0.1:8000/forum/unsubscribe/natal-mexicano-5/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

######

GET http://localhost:8000/forum/detail/ano-novo-200/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52


###TESTES DE EVENTO###



POST http://localhost:8000/forum/event/register/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
  "title": "natal mexicano",
  "description": "This is an example description for the event.",
  "date": "2025-01-20",
  "location":"rua da casa do carvalho"
}

######

GET http://localhost:8000/forum/list/?page=1
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52

######

GET  http://localhost:8000/forum/event/detail/natal-mexicano-4/ 
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json


######

POST  http://localhost:8000/forum/event/edit/teste-de-evento/ 
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
  "title": "teste de evento",
  "description": "This is an example description for the forum.",
  "date": "2025-01-29",
  "location":"rua da casa do carvalho"
}

######

POST  http://localhost:8000/forum/delete/teste-de-evento/ HTTP/1.1
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

######

POST http://localhost:8000/forum/review/register/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
  "five_star": "4",
  "forum_slug": "natal-mexicano-4"
}


######


POST http://localhost:8000/forum/review/edit/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

{
  "five_star": "1",
  "forum_slug": "natal-mexicano"
}


######

POST http://127.0.0.1:8000/forum/review/delete/natal-mexicano-4/
Authorization: Token 079b7a2f44ee70858c702aa697214acf30cccc52
Content-Type: application/json

######