
POST http://localhost:8000/forum/register/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

{
  "title": "teste",
  "description": "This is an example description for the forum."
}

######

POST  http://localhost:8000/forum/edit/teste-1/ 
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597
Content-Type: application/json

{
  "title": "ano novo 1",
  "description": "This is an example description for the forum."
}

######

POST  http://localhost:8000/forum/delete/teste/ HTTP/1.1
Authorization: Token 0b32659e7c17349859dd9e123c9ace264aed9520
Content-Type: application/json

######

GET http://localhost:8000/forum/list/?page=1
Authorization: Token 0b32659e7c17349859dd9e123c9ace264aed9520

######

GET http://localhost:8000/forum/list/?search=natal
Authorization: Token c55d674ffd9e375f61d3be0a32c5d7f6403404a1

######

POST http://localhost:8000/forum/subscribe/teste-1/
Authorization: Token 9d5f607f8c7b39b348c783c96e983888daaa9597

######

GET http://localhost:8000/forum/detail/meu-forum/
Authorization: Token 0b32659e7c17349859dd9e123c9ace264aed9520
