# Generated by Django 5.1.3 on 2025-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='did_review',
            field=models.BooleanField(default=False),
        ),
    ]
