# Generated by Django 5.1.3 on 2025-01-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('forum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.forum')),
                ('date', models.DateField()),
                ('location', models.TextField(max_length=1023)),
                ('cancelled', models.BooleanField(default=False)),
                ('five_star_mean', models.FloatField(default=0.0)),
            ],
            bases=('forum.forum',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_star', models.PositiveSmallIntegerField(choices=[(1, '1 - Terrível'), (2, '2 - Ruim'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Excelente')])),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='forum.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.userprofile')),
            ],
        ),
    ]
