# Generated by Django 5.1.4 on 2025-01-19 20:57

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_review_did_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.directory_path),
        ),
    ]
