# Generated by Django 5.1.4 on 2025-01-19 21:44

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='banner_image_low',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.directory_path),
        ),
    ]
