# Generated by Django 5.1.3 on 2025-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_user_review_user_profile_alter_review_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
